on:
  push:
    branches:
      - master
      - main
  pull_request:
    types: [opened, synchronize, reopened]

name: SonarQube Scan
jobs:
  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v2
      
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Adjust the Java version if needed

      - name: SonarQube Scan
        run: |
          ./gradlew sonarqube -Dsonar.host.url=https://your-sonarqube-server
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
